#!/bin/bash
set -e

IFACE="ens3"
CAPTURE_FILE="packets.log"

echo "[*] Capturing packets on $IFACE"
sudo tcpdump_pfring -ni "$IFACE" -l \
'not port 22 and ip and tcp and ((ip[2:2]-((ip[0]&0x0f)<<2)-((tcp[12]&0xf0)>>2))>0)' \
| tee "$CAPTURE_FILE"
